# Site settings
title: Yogesh CV
description: A little bit about my self
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yogesh Maher
user_description: I belive in evolving with the technologies and all the new tech came accross in your path, this is the path I follow. I have started Programing with simple Hello World Text and now evolving my skills as per the industry requirements. I follow my dreams and to love code.
user_title: Software Developer
email: yogeshmaher64@gmail.com
# twitter_username: lorem_ipsum
github_username:  https://github.com/yo-yogesh
gplus_username:  https://plus.google.com/u/0/+YOGESHMAHER64

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
